import type { HelpArticle } from "../types";

/**
 * The Help Centre's coverage of the dashboard: the screen everyone lands on, the
 * cards they arrange on it, and the cards they build themselves.
 *
 * Authored by hand rather than assembled per module (the same treatment Getting
 * Started gets) because a dashboard is the one feature where the interesting
 * part is not "which button" but "what is and is not possible, and why" — the
 * closed field catalogue, the difference between a rule that hides a card before
 * it loads and one that hides it afterwards, and the fact that a screen-size
 * rule hides nothing at all from anybody determined to look.
 *
 * Every number quoted below is read out of LIMITS in src/lib/dashboard/config.ts
 * and the caps in src/lib/dashboard/compile.ts. If one of those changes, these
 * articles are wrong and must change with it.
 */
export const dashboardArticles: HelpArticle[] = [
  {
    slug: "dashboards-overview",
    title: "Your dashboard: how it is put together",
    summary: "Dashboards, tabs, sections and cards — what each level is for, and why the screen is yours alone.",
    category: "getting-started",
    audience: "everyone",
    keywords: ["dashboard", "home", "home screen", "tabs", "sections", "cards", "layout", "widgets", "tiles"],
    body: [
      { type: "p", text: "Your dashboard is the screen you land on when you sign in. It summarises what needs you — new leads, work due, headline numbers — and every tile on it is a link into the list behind it. It is also **yours**: you arrange it, and nothing you do to it changes anybody else's screen." },
      { type: "h", text: "Four levels, nested" },
      { type: "table", headers: ["Level", "What it is", "Reach for it when"], rows: [
        ["Dashboard", "A whole named screen with its own address.", "You want a separate screen for a separate job — a sales screen and a workshop screen, rather than one screen with everything on it."],
        ["Tab", "A page within a dashboard.", "One screen has grown past one screenful. A tab beats scrolling, because nobody reads past the fold."],
        ["Section", "A titled block of cards that owns a share of the width.", "Two groups belong beside each other — \"Today\" next to \"This month\" — as blocks, rather than as loose cards the grid happened to line up that way."],
        ["Card", "The thing that actually shows something: a number, a list, a chart, a gauge, a note or a link.", "Always. Everything above exists only to place cards."],
      ] },
      { type: "p", text: "A tab is laid out in up to four columns, and each card says how many of those columns it takes up. There is no drag-anywhere, pin-it-to-a-pixel layout: you choose a width and the grid places the card. That is deliberate — a layout pinned to exact positions is wrong at the next screen size, and on a phone everything drops into a single column regardless." },
      { type: "h", text: "The cards you get as standard" },
      { type: "p", text: "Twelve cards are built into the app. They stay available whatever else you build, and they are the ones a brand-new dashboard starts with." },
      { type: "table", headers: ["Card", "What it shows"], rows: [
        ["System alerts", "Warns when the AI assistant or a security check is failing. Quiet otherwise."],
        ["Sales stats", "New leads, won value, open leads and deliveries this month."],
        ["Brand-new", "Leads that have come in and nobody has opened yet."],
        ["Pipeline snapshot", "Open leads by stage, with the total value in play."],
        ["Month targets", "Progress rings against this month's targets."],
        ["Agenda", "Your team's planned activities for today and tomorrow."],
        ["Out for signature", "Quotes sent for signature and who they are waiting on. Hidden when nothing is out."],
        ["Needs attention", "Open leads with no next step, and quotes left unsigned."],
        ["Latest activity", "New leads, logged conversations and quote events, newest first."],
        ["Service stats", "Open job cards, services completed, vehicles due and fleet size."],
        ["Workshop agenda", "Workshop activities booked for today and tomorrow."],
        ["Vehicles due for service", "Vehicles overdue or coming up for a service."],
      ] },
      { type: "p", text: "The last three belong to the vehicle and workshop pack: if your dealership does not have it switched on, those cards do not exist for anyone. The rest depend on your permissions, so your dashboard may be shorter than a colleague's." },
      { type: "h", text: "Yours is yours" },
      { type: "p", text: "Dashboards are per person. Building one does not publish it, there is no way to push yours onto a colleague, and nobody else can open it — a dashboard address that is not yours simply does not exist as far as your account is concerned." },
      { type: "callout", tone: "info", text: "You do not have to build anything. Until you change something you get the standard dashboard, and it keeps up with the app — a card added in a later release appears on it without you lifting a finger. The first change you make turns it into your own screen, and from then on it is yours to keep." },
      { type: "callout", tone: "tip", text: "A card never shows you a row you could not open on its own page. See **What a card can and cannot show** for what that means in practice." },
    ],
  },
  {
    slug: "dashboards-arranging",
    title: "Adding, moving and removing cards",
    summary: "Customise mode, the grip handle, keyboard arrows, and why there is no Save button.",
    category: "getting-started",
    audience: "everyone",
    keywords: ["customise", "customize", "arrange", "rearrange", "drag", "reorder", "move card", "remove card", "add card", "reset", "save"],
    body: [
      { type: "p", text: "Arranging your own dashboard needs no special permission. If you can sign in, you can move your cards around." },
      { type: "steps", items: [
        "Click **Customise** at the top of the dashboard. Every card grows a dashed outline, a grip handle and a remove button.",
        "Drag a card by its **grip handle** to move it. The cards around it shuffle live as you drag, so the gap you are about to drop into is the gap you can see.",
        "Prefer the keyboard? Move focus to a grip handle and use the **arrow keys**.",
        "Click the **✕** on a card to take it off your screen. Nothing is deleted — the records it was summarising are untouched, and you can add the card back.",
        "Add cards from the **Add a card** row. It only ever offers cards you are already allowed to see.",
        "Click **Done** when you have finished.",
      ] },
      { type: "callout", tone: "warning", text: "**There is no Save button, and you should not go looking for one.** Every move, addition and removal saves the moment you make it. If a save ever fails, the card springs back to where it was and a message tells you — so the screen you are looking at is always the screen that is stored." },
      { type: "h", text: "On a phone" },
      { type: "p", text: "Hold a grip handle for a moment before you start dragging. The short delay is what lets an ordinary swipe scroll the page instead of picking a card up." },
      { type: "h", text: "Cards that come and go" },
      { type: "p", text: "Some cards only appear when they have something to show — **Out for signature** is empty most of the week, and **System alerts** stays quiet until something is wrong. In the add-card row these are badged **when relevant**. Adding one and seeing nothing appear is not a fault; it means there is nothing to show yet." },
      { type: "h", text: "Reset to default" },
      { type: "p", text: "While you are customising, **Reset to default** puts the screen back to the standard arrangement — every card you are entitled to, in the order the app ships them. It is the way out of an arrangement you have made a mess of." },
      { type: "callout", tone: "tip", text: "If you remove every card, the dashboard stays empty rather than quietly refilling itself. That is on purpose: an empty screen is a choice, and undoing it silently would make the remove button look broken." },
    ],
  },
  {
    slug: "dashboards-build-a-card",
    title: "Building a card of your own",
    summary: "Source, filters, mine or the team, period, sort and limit — and which of the four card styles to use.",
    category: "getting-started",
    audience: "everyone",
    keywords: ["build card", "custom card", "query", "filter", "stat", "list", "chart", "gauge", "period", "sort", "limit", "source"],
    body: [
      { type: "p", text: "Besides the twelve built-in cards you can build your own. A card asks one question of one kind of record and shows the answer. Everything below is one card." },
      { type: "h", text: "The six things a card is made of" },
      { type: "steps", items: [
        "**Source** — the kind of record: Leads, Quotes, Activities, Contacts, Job cards or Vehicles. You are only offered the sources you already have access to; job cards and vehicles need the vehicle and workshop pack.",
        "**Filters** — up to eight tests that a record has to pass. The comparisons on offer depend on the field: text can contain something, a number or an amount can be greater or less than, a status can be one of a list, a date can be before or after, and anything can be empty or not empty.",
        "**Mine or the team** — whether the card is about your own records or everybody's.",
        "**Period** — a time window: All time, Today, Last 7 days, Last 30 days, Last 90 days, This month, Last month or This year. You also choose which date the window measures — when a lead was created, when it last moved stage, when a quote was signed, and so on.",
        "**Sort** — which field orders the rows, and which way round.",
        "**Limit** — how many rows a list may show. Eight by default, fifty at most.",
      ] },
      { type: "h", text: "A worked example: big open deals, oldest first" },
      { type: "p", text: "Say you want the open leads worth more than R50 000, with the ones that have been sitting longest at the top." },
      { type: "steps", items: [
        "Source: **Leads**.",
        "Filter: **Status is Open**.",
        "Filter: **Value is greater than 50000**. Amounts are typed in rands, so that is R50 000 — you never type cents.",
        "Scope: **the team**, if you are looking after other people's pipelines; **mine** if it is your own.",
        "Period: **All time**, because you want the old ones, not the recent ones.",
        "Sort: **In stage since**, ascending — longest untouched at the top.",
        "Style: **List**, with the columns Name, Stage, Value and Owner.",
      ] },
      { type: "callout", tone: "warning", text: "Every period looks **backwards from today** — \"the last 7 days\", \"this month\". There is no \"older than\" window, so a card cannot filter for records nobody has touched in a week. Sort oldest-first instead, as above. Typing a fixed date into a filter looks like it works and then quietly stops being true the day after you type it." },
      { type: "callout", tone: "info", text: "**Mine** can only narrow. Choosing the team does not widen anything — if your role only lets you see your own leads, you get your own leads either way. The switch exists so that someone who *can* see the whole team's pipeline can still build a card about their own." },
      { type: "h", text: "Which style to use" },
      { type: "table", headers: ["Style", "Shows", "Use it when"], rows: [
        ["Stat", "One big number — a count, or a total, average, smallest or largest of a number or amount.", "The answer is a single figure you want to see from across the room."],
        ["List", "Rows and up to six columns. Every row opens its record.", "You are going to act on the individual records, not just count them."],
        ["Chart", "A bar or donut chart of one number broken down by a field.", "The shape of the split matters — leads by stage, job cards by priority."],
        ["Gauge", "A progress ring against a target you set.", "There is a goal and you want to see how far along it is."],
      ] },
      { type: "h", text: "Details worth knowing" },
      { type: "list", items: [
        "**Stat cards** can show the change against the previous period, and that only works for **This month**, which has Last month to compare against. Any other period shows no comparison rather than an invented one. A stat card can also be given a link, so clicking it opens the list behind the number.",
        "**List cards** show a footer such as \"Showing 8 of 231\" when there were more matches than rows. Leave the columns alone and the card uses the sensible defaults for that source.",
        "**Charts** group by a field with a small set of values — status, stage, owner, priority, province. Grouping by a name or a date would give you one bar per record, which is not a chart. A chart carries at most 24 slices, and when it could not count everything it says **Partial view** rather than quietly under-reporting.",
        "**Gauges** need a target. Set it against the same thing the card counts.",
      ] },
      { type: "callout", tone: "tip", text: "If a card cannot be loaded — a field it used has gone, or your access to something changed — it says so inside its own box and every other card on the screen carries on as normal. One bad card costs exactly one card." },
    ],
  },
  {
    slug: "dashboards-notes-and-layout",
    title: "Notes, headings, shortcuts and containers",
    summary: "The cards that ask the database nothing: text notes, dividers, link buttons and the grid and stack containers.",
    category: "getting-started",
    audience: "everyone",
    keywords: ["note", "markdown", "text", "heading", "divider", "button", "shortcut", "link", "grid", "stack", "container", "group"],
    body: [
      { type: "p", text: "Not every card is a question. Four kinds show something you put there yourself, and cost nothing to display." },
      { type: "h", text: "Notes" },
      { type: "p", text: "A block of text pinned to the dashboard — a reminder for the team, this month's focus, the number to phone when the workshop is full. Up to 4 000 characters." },
      { type: "list", items: [
        "A blank line starts a new paragraph. Single line breaks are kept as they are.",
        "Text appears exactly as you type it. Formatting marks are not turned into bold or headings, and anything that looks like code or a web address is shown as plain text rather than acted on.",
      ] },
      { type: "h", text: "Headings" },
      { type: "p", text: "A line of text used as a divider between groups of cards. A heading takes the full width of the row by default, which is what makes it read as a break rather than as another tile." },
      { type: "h", text: "Link buttons" },
      { type: "p", text: "A shortcut tile — one click to the page you open twenty times a day. You can give it a title and an icon; without a title it shows where it goes." },
      { type: "callout", tone: "warning", text: "A link button can only point at a page **inside this app**. An address anywhere else is refused, and a saved one that slips through is not shown at all. A button sitting on the company dashboard is trusted in a way an emailed link never is, which is exactly what would make it worth faking." },
      { type: "h", text: "Grids and stacks" },
      { type: "p", text: "Containers hold other cards, so a group can be moved and hidden as one thing." },
      { type: "list", items: [
        "**Grid** — its own little grid of two, three or four columns inside one slot of the page.",
        "**Stack** — cards in a line. A vertical stack piles them up; a horizontal stack sets them side by side, wraps when it runs out of room, and becomes a single column on a phone.",
        "Containers can sit inside containers up to **three deep**. Past that is more nesting than anyone can hold in their head.",
      ] },
      { type: "callout", tone: "info", text: "A container with nothing left showing inside it disappears completely, rather than leaving an empty box on the screen." },
    ],
  },
  {
    slug: "dashboards-visibility",
    title: "Showing a card only when it matters",
    summary: "The three kinds of visibility rule, when each is decided, and why a screen-size rule hides nothing from anybody.",
    category: "getting-started",
    audience: "everyone",
    keywords: ["visibility", "condition", "hide", "show when", "role", "permission", "time", "empty", "screen size", "mobile", "breakpoint"],
    body: [
      { type: "p", text: "Any card — and any section or tab — can carry rules that decide whether it appears. No rules means it always appears. Several rules means they all have to be true; there are explicit **any of** and **not** groups when that is not what you want." },
      { type: "p", text: "The rules come in three kinds, and the difference between them is not a detail. It decides whether anything was fetched, and whether anything was sent to your browser." },
      { type: "h", text: "1. Who is looking, and when" },
      { type: "list", items: [
        "**Person** — named individuals.",
        "**Role** — any one of a list of roles.",
        "**Permission** — anyone holding a particular right.",
        "**Module** — the dealership has a particular pack switched on.",
        "**Time** — a time of day, and/or particular days of the week, in the workspace's own timezone. A window that crosses midnight (after 22:00, before 06:00) works properly — a night-shift card really does show at 02:00.",
      ] },
      { type: "p", text: "These are settled **before the card is loaded**. A card they hide is never queried and its contents never reach the browser at all. They make the screen quieter and genuinely cheaper." },
      { type: "h", text: "2. Something about the card's own data" },
      { type: "p", text: "\"Only when it has rows\" is the common one. A rule like this asks about the result the card produced, which means **the card has to run first**. It buys you a quieter screen, not a faster one — the query has already happened by the time the answer exists, and the result is then thrown away." },
      { type: "p", text: "Two things about its own results are available to a rule, and what they mean depends on the card:" },
      { type: "table", headers: ["Card", "Count is", "Total is"], rows: [
        ["Stat", "How many records matched", "The number the card shows"],
        ["List", "How many rows are on the card", "How many records matched altogether, before the row limit"],
        ["Chart", "How many slices there are", "The added-up value of all of them"],
        ["Gauge", "How many records matched", "The number being measured against the target"],
        ["Grid or stack", "How many of its cards are showing", "—"],
      ] },
      { type: "callout", tone: "info", text: "A card that could not be loaded has no count at all — so a card set to appear \"only when it has rows\" stays out of the way when it breaks, instead of leaving a failed box on your screen." },
      { type: "h", text: "3. Screen size" },
      { type: "p", text: "A screen rule shows or hides a card at phone, tablet or desktop widths. **It only hides things in the browser. The information was already sent there.** A card hidden by a screen rule was fetched, was included in the page, and is sitting on the device — hidden by the same mechanism that hides a column on a narrow table, and just as easy to look at." },
      { type: "callout", tone: "warning", text: "**A screen rule is a layout tool and nothing else. Never use one to keep something from someone.** Hiding a wide table on a phone is a perfectly good reason to use it. Keeping a number away from a colleague is not, and doing it that way means believing something is hidden when it is not. If a person should not see something, that is a matter for their permissions — or for a who-is-looking rule, which is decided before anything is sent." },
      { type: "h", text: "None of this is access control" },
      { type: "p", text: "Visibility rules decide what is **shown**, never what you are **allowed** to see. Your permissions and the dealership's modules are checked first, every time, for every card. Strip every rule out of your own dashboard and you will not see one extra record." },
      { type: "callout", tone: "tip", text: "One list may hold up to twelve rules, and groups nest three deep. If you need more than that on one card, it is usually two cards." },
    ],
  },
  {
    slug: "dashboards-what-cards-show",
    title: "What a card can and cannot show",
    summary: "Why contact details and free-text notes are not available to cards, and why a card can never show a record you could not open.",
    category: "getting-started",
    audience: "everyone",
    keywords: ["email", "phone", "contact details", "notes", "privacy", "permissions", "what can i see", "deleted", "value", "security"],
    body: [
      { type: "p", text: "A card can only ask about fields the app hands it, and that list is written out by hand rather than taken from the database. Some things are on it, and some things are kept off it on purpose." },
      { type: "h", text: "What is not on offer, and why" },
      { type: "list", items: [
        "**Email addresses and phone numbers.** They exist on leads, contacts and elsewhere, and they are exactly what you would want on a \"leads to call\" card.",
        "**Free-text notes** — notes on a record, research, the reason something was deleted, workshop check-in notes. In practice these hold prices, personal circumstances and opinions about the customer.",
        "**Tamper-evidence data** — signing tokens, IP addresses, document fingerprints. Not business information; they exist to prove a document was not altered.",
      ] },
      { type: "p", text: "This is a design decision with a reason behind it, rather than something still to be added. A dashboard is a screen people leave open in a shared office, glance at over each other's shoulders and screenshot into chats. A list card is not the place from which to read off a marketing list. Contact details are reached from the record itself, where opening the record is a deliberate act with a trail behind it rather than an ambient display on a monitor." },
      { type: "callout", tone: "tip", text: "Build the card on the fields that are available — name, stage, owner, value, dates — and click through to the record when you need to phone somebody. That is one extra click, and it is the click that keeps the record of who looked." },
      { type: "h", text: "What everyone sees" },
      { type: "list", items: [
        "**A card never shows a row you could not open on its own page.** Cards are scoped exactly the way the record lists are: a card is not a way around a page.",
        "**Deleted records never appear.** Anything in the recycle bin is left out of every card, always, with no setting to turn that off.",
        "**Some fields carry their own permission.** Deal value is the one that matters most: if you are not shown what a lead is worth on the lead itself, a card cannot show it, total it, or sort by it either. Ranking rows by a number you are not allowed to see would give it away as surely as printing it.",
        "**Mine and the team can only narrow.** Neither setting widens what you may see.",
        "**Dashboards are per person.** Yours is yours; building one does not publish it to anybody.",
      ] },
      { type: "callout", tone: "info", text: "If a card names something that no longer exists — a field that was retired, or one your access changed — it is dropped and the dashboard tells you at the top of the page which cards were removed and why. It never fails silently, and it never falls back to showing more than it was built to show." },
    ],
  },
  {
    slug: "dashboards-limits",
    title: "Dashboard limits",
    summary: "The ceilings on dashboards, tabs, sections, cards, filters and rules — and what happens when you reach one.",
    category: "getting-started",
    audience: "everyone",
    keywords: ["limit", "maximum", "how many", "cap", "too many cards", "ceiling"],
    body: [
      { type: "p", text: "Everything on a dashboard costs something — every card that asks a question is a query on the first screen every user loads — so the sizes are capped." },
      { type: "table", headers: ["Thing", "Limit"], rows: [
        ["Dashboards per person", "12"],
        ["Tabs in one dashboard", "12"],
        ["Sections in one tab", "12"],
        ["Cards in one tab", "40, counting every card including those inside containers"],
        ["Cards in one section", "24"],
        ["Containers nested inside containers", "3 deep"],
        ["Filters on one card", "8"],
        ["Columns on a list card", "6"],
        ["Rows a list card may show", "50 (8 by default)"],
        ["Values in one \"is one of\" filter", "50"],
        ["Slices in one chart", "24"],
        ["Visibility rules in one list", "12, with groups nesting 3 deep"],
        ["Length of a title", "80 characters"],
        ["Length of a note", "4 000 characters"],
      ] },
      { type: "callout", tone: "info", text: "Going over a limit is refused when you save, with a message saying which one you hit — nothing is stored half-done. A dashboard that is already over a limit is trimmed from the end when it loads, so the top of the screen, which is the part you actually look at, stays exactly as you left it." },
      { type: "p", text: "If you are pushing against the cards-per-tab limit, that is usually the app telling you the tab has become two screens. Split it into two tabs, or a second dashboard." },
    ],
  },
];
