import type { HelpArticle } from "../types";

export const gettingStartedArticles: HelpArticle[] = [
  {
    slug: "welcome",
    title: "Welcome to Denago CRM",
    summary: "What the system does and how this manual is organised.",
    category: "getting-started",
    audience: "everyone",
    keywords: ["overview", "introduction", "welcome", "what is", "getting started", "home"],
    body: [
      { type: "p", text: "Denago CRM is the single system that runs the dealership — from the first enquiry through the sale, delivery, workshop servicing and long-term customer care. It replaces spreadsheets and scattered chats with one place where every lead, quote, vehicle, job card and conversation lives together." },
      { type: "h", text: "What you can do here" },
      { type: "list", items: [
        "**Sell** — capture leads, work them through the pipeline, build quotes, take e-signatures and hand over vehicles.",
        "**Stock** — track every physical unit from purchase order to delivery, with reservations and inspections.",
        "**Service** — book workshop jobs, run job cards, schedule services and manage warranties.",
        "**Engage** — reply to WhatsApp, Messenger, Instagram and Telegram from one inbox, run campaigns and surveys, and answer support tickets.",
        "**Understand** — dashboards, reports, targets and forecasts show how the business is tracking.",
      ] },
      { type: "h", text: "How this manual is organised" },
      { type: "p", text: "The Help Centre mirrors the app's own menu. Each section below matches a group in the sidebar, so if you can find a feature in the app you can find its guide here. Use the search box at the top of the Help Centre to jump straight to any topic." },
      { type: "callout", tone: "tip", text: "You only see the modules your account has access to. If a section in this manual describes something you can't find, your administrator may not have enabled it for your role." },
    ],
  },
  {
    slug: "signing-in",
    title: "Signing in & keeping your account secure",
    summary: "Log in, set up two-factor authentication, and recover access.",
    category: "getting-started",
    audience: "everyone",
    keywords: ["login", "log in", "sign in", "password", "2fa", "two-factor", "otp", "authenticator", "passkey", "security"],
    body: [
      { type: "p", text: "You sign in with your work email and password. Depending on how your administrator configured your account, you may also be asked for a second factor — a code from an authenticator app, a code emailed to you, or a passkey." },
      { type: "h", text: "Sign in" },
      { type: "steps", items: [
        "Go to the CRM address in your browser and enter your email and password.",
        "If prompted, enter your six-digit verification code, or approve with your passkey.",
        "You'll land on your Dashboard.",
      ] },
      { type: "h", text: "Turn on two-factor authentication" },
      { type: "p", text: "Two-factor authentication (2FA) adds a second step so a stolen password alone can't get in. Set it up under **Settings → My Account** (or Security)." },
      { type: "steps", items: [
        "Open Settings and find the two-factor / authenticator option.",
        "Scan the QR code with an authenticator app (Google Authenticator, Authy, 1Password, etc.).",
        "Enter the code the app shows to confirm.",
        "Save the one-time backup codes somewhere safe — they let you in if you lose your phone.",
      ] },
      { type: "callout", tone: "warning", text: "For your protection, sessions expire after a period of inactivity, and there is a hard re-login every few days. Being asked to sign in again is normal, not a fault." },
      { type: "h", text: "If you're locked out" },
      { type: "p", text: "Use a saved backup code, or ask an administrator to help — they can reset your password and, if needed, sign you out of all devices from **Settings → Sessions & devices**." },
    ],
  },
  {
    slug: "finding-your-way-around",
    title: "Finding your way around",
    summary: "The sidebar, the dashboard, and how to search from anywhere.",
    category: "getting-started",
    audience: "everyone",
    keywords: ["navigation", "sidebar", "menu", "dashboard", "search", "command", "layout", "find"],
    body: [
      { type: "p", text: "The app has three constants: the **sidebar** on the left for navigation, the **top bar** for search and quick actions, and the main area where your work happens." },
      { type: "h", text: "The sidebar" },
      { type: "p", text: "Modules are grouped by the kind of work they do — Social, CRM, Marketing, Stock, Workshop, Automation and so on. You only see the groups and links your role can access, so your sidebar may be shorter than a colleague's." },
      { type: "h", text: "The dashboard" },
      { type: "p", text: "Your home screen summarises what needs attention — new leads, tasks due, and headline numbers. Tiles are links: click one to jump straight to the underlying list, already filtered." },
      { type: "h", text: "Search from anywhere" },
      { type: "p", text: "The quickest way to reach a record is the global search / command menu in the top bar." },
      { type: "steps", items: [
        "Click the search box in the top bar (or press the keyboard shortcut shown in it).",
        "Start typing a name, phone number, quote number or vehicle.",
        "Pick a result to jump straight to it, or choose a quick action such as creating a new lead.",
      ] },
      { type: "callout", tone: "tip", text: "Search looks across leads, contacts, quotes, vehicles and more at once — it's usually faster than opening a module and filtering." },
    ],
  },
  {
    slug: "who-can-see-what",
    title: "Who can see what: roles & permissions",
    summary: "How access is decided — modules, roles and record ownership.",
    category: "getting-started",
    audience: "everyone",
    keywords: ["permissions", "roles", "access", "modules", "owner", "member", "visibility", "why can't i"],
    body: [
      { type: "p", text: "What you can see and do is governed by three things working together. Understanding them explains why a colleague might see a button you don't." },
      { type: "list", items: [
        "**Modules** — the broad areas switched on for your account (CRM, Workshop, Reports, Inbox…). A module that's off hides its whole section.",
        "**Permissions** — finer-grained rights within a module (for example, view all leads vs. only your own; manage stock vs. just view it).",
        "**Ownership** — many records have an owner. Some permissions grant access to everything; others only to records assigned to you or your team.",
      ] },
      { type: "callout", tone: "info", text: "The **owner** role sees and manages everything. Everyone else gets exactly the modules and permissions an administrator assigns." },
      { type: "p", text: "If you need access to something, ask an administrator — they can adjust your role or permissions under Settings → Team & access. Administrators should see the Administration section of this manual." },
    ],
  },
  {
    slug: "install-on-your-phone",
    title: "Install it on your phone & get notifications",
    summary: "Install the existing PWA, use Offline Field Mode, and receive notifications.",
    category: "getting-started",
    audience: "everyone",
    keywords: ["mobile", "phone", "install", "pwa", "app", "notifications", "push", "telegram", "home screen"],
    body: [
      { type: "p", text: "The CRM is a web app that also installs like a native one, so you can run it from your home screen and receive push notifications on the move." },
      { type: "h", text: "Install it" },
      { type: "steps", items: [
        "Open the CRM in your phone's browser and sign in.",
        "On iPhone (Safari): tap Share, then **Add to Home Screen**.",
        "On Android (Chrome): open the menu and choose **Install app** / **Add to Home screen**.",
        "Open it from the new icon — it runs full-screen, and installed sessions stay signed in longer.",
      ] },
      { type: "callout", tone: "info", text: "This is an installable Progressive Web App (PWA), not an App Store or Play Store download. Updates arrive automatically with the website." },
      { type: "h", text: "Turn on notifications" },
      { type: "p", text: "Allow notifications when prompted (or enable them under Settings → Notifications) to be alerted about things like new leads, handed-over chats and tasks due." },
      { type: "h", text: "Launch from Telegram" },
      { type: "p", text: "If your dealership has enabled it, you can also open the CRM straight from a Telegram link and be signed in automatically. See the Administration section for how to set that up and link your account." },
    ],
  },
  {
    slug: "everyday-conventions",
    title: "Conventions used everywhere",
    summary: "Patterns that repeat across the app — modals, editing, and undo.",
    category: "getting-started",
    audience: "everyone",
    keywords: ["conventions", "modal", "dialog", "edit", "delete", "trash", "undo", "audit", "how to", "save"],
    body: [
      { type: "p", text: "Once you learn a few patterns that repeat throughout the app, every module feels familiar." },
      { type: "list", items: [
        "**Add & edit in place** — creating or editing a record usually opens a pop-up form (a modal) over your current screen. Fill it in and save; you stay where you were.",
        "**Lists & filters** — module home screens are lists you can search and filter. On phones the same lists become tidy stacked cards.",
        "**Nothing is truly lost** — deleting moves a record to the recycle bin for 60 days, where it can be restored. See Reporting & records → Recycle bin.",
        "**Everything is logged** — important actions are recorded in the audit log, so there's always a history of who changed what.",
      ] },
      { type: "callout", tone: "tip", text: "Look for a confirmation step before anything destructive. If you delete something by accident, head to the recycle bin — you have 60 days to bring it back." },
    ],
  },

  {
    slug: "offline-field-mode",
    title: "Working offline on mobile",
    summary: "Download field records, capture work without signal, and safely synchronise it later.",
    category: "getting-started",
    audience: "everyone",
    keywords: ["offline", "online", "sync", "synchronise", "mobile", "pwa", "no signal", "pending", "conflict", "photos", "signature", "delivery", "job card"],
    body: [
      { type: "p", text: "The installed CRM can keep essential field work moving when a phone has weak or no connectivity. Offline Field Mode covers leads, contacts, active job cards, inspections, delivery handovers, condition notes, photos and customer delivery signatures. It does not require an App Store or Play Store download." },
      { type: "h", text: "Prepare before leaving coverage" },
      { type: "steps", items: [
        "Open the CRM while online and tap the permanent **Online** indicator.",
        "Open **Offline field workspace** and choose **Refresh offline data**.",
        "Confirm the downloaded time shown beside the status. Only records your current role may access are included.",
        "Leave the installed app available on the phone. If it is reopened without a connection, use the cached Offline field workspace.",
      ] },
      { type: "h", text: "Know your connection state" },
      { type: "list", items: [
        "**Online** with a green dot means the server is reachable.",
        "**Offline** with an amber dot means supported saves are going to this device's outbox.",
        "A number beside the indicator is the count of changes still waiting.",
        "**Syncing…** means queued work is being checked and sent one operation at a time.",
      ] },
      { type: "h", text: "What can be captured offline" },
      { type: "table", headers: ["Area", "Offline capability"], rows: [
        ["Leads", "View downloaded leads and capture new leads. Lead edit forms already open on the device can queue changes."],
        ["Contacts", "View downloaded contacts and capture new contacts. Contact edit forms already open on the device can queue changes."],
        ["Job cards", "View active downloaded cards; update check-in/check-out notes and inspection results; capture condition and inspection photos."],
        ["Deliveries", "View scheduled handovers; complete the checklist, capture the driver's name and customer signature, and attach delivery photos."],
      ] },
      { type: "h", text: "Synchronisation and conflicts" },
      { type: "p", text: "The app retries when connectivity returns, when the app regains focus, or when you choose **Synchronise now**. Every queued change has a unique identity, so retrying cannot apply the same operation twice. The server rechecks your session, tenant, permissions and record ownership before accepting anything." },
      { type: "callout", tone: "warning", text: "If somebody changed the same lead, contact, job card or delivery after your copy was downloaded, the app marks your item as a conflict instead of overwriting their work. Open the current record, compare it, and submit the intended change again." },
      { type: "h", text: "Photos and signatures" },
      { type: "p", text: "Photos and drawn delivery signatures remain on the device until the server confirms them. Photos are sent as individual queued operations; do not clear site data or uninstall the PWA while items are pending. A delivery is not reported as complete until its queued checklist and signature have been accepted." },
      { type: "h", text: "Security and retention" },
      { type: "list", items: [
        "Offline data is partitioned by both tenant and user.",
        "Every replay is authenticated and tenant-scoped; changing the queued tenant or user is refused.",
        "Signing out removes local CRM records, queued files and the authenticated offline shell from that device.",
        "Switching user or workspace purges data that does not match the active identity.",
        "Queued operations expire after 72 hours and require review; the app does not silently submit stale work.",
        "Integration secrets, credentials, financial approvals, user administration, deletion and system logs are never available offline.",
      ] },
      { type: "h", text: "Troubleshooting" },
      { type: "list", items: [
        "**No downloaded records** — reconnect, open Offline field workspace and refresh.",
        "**A change stays pending** — keep the app open online and choose Synchronise now.",
        "**Conflict** — reload the live record and re-enter the change after reviewing the newer version.",
        "**Failed** — read the item in the Pending tab. Unexpected server failures are also recorded under Settings → System Log with scope **offline-sync**.",
        "**Phone storage is low** — synchronise photos, then let the app remove confirmed local copies. Browser storage can be evicted by the operating system.",
      ] },
    ],
  },
];
