import type { HelpArticle } from "../types";

/**
 * The journey engine, hand-authored — the same treatment as getting-started.ts
 * and for the same reason: this is the part of the app that changed most and the
 * part a wrong sentence costs the most in, because a journey that misfires sends
 * real messages to real customers.
 *
 * These slugs REPLACE the ones in data/marketing.json (see REPLACED_MARKETING_SLUGS
 * in ../content.ts). `automations-rules` is kept rather than dropped: the rules
 * engine is retired, but "automation rule" is still the phrase people type, and
 * an article that says where it went is worth more than a missing one.
 */
export const journeysArticles: HelpArticle[] = [
  {
    slug: "automations-rules",
    title: "Automation rules are now journeys",
    summary: "The old when-then automation rules have been retired. Your rules were converted into journeys — here is where they went and what changed.",
    category: "marketing",
    audience: "admins",
    keywords: [
      "automation rule",
      "automation rules",
      "automations",
      "rules",
      "when then",
      "workflow",
      "lead workflow",
      "trigger",
      "retired",
      "moved",
      "where did",
      "new automation",
      "run log",
    ],
    body: [
      { type: "p", text: "The old **Automations** screen — one trigger, one action, a list of when-then rules — no longer exists. Everything it did is now done by **Journeys**, which is the same idea with waits, branches, SMS, tags, versioning and a proper history behind it." },
      { type: "callout", tone: "info", text: "Nothing was lost. Every rule you had configured was converted into a journey automatically when the change went in. Old links to the Automations page still work — they take you to Journeys." },
      { type: "h", text: "Where things went" },
      { type: "table", headers: ["The old rules screen", "Where it is now"], rows: [
        ["The Automations link in the sidebar", "**Automation → Journeys** in the sidebar"],
        ["The New automation button", "**+ Create a journey** at the top of the Journeys page"],
        ["The When trigger", "**1. Enrollment trigger** in the journey builder — the same list, plus segment, anniversary and win-back triggers"],
        ["The \"Only if…\" restrictions", "**3. Optional entry filters** — lead source, province, minimum lead value"],
        ["The single Then action", "**4. Journey steps** — as many steps as you need, in order, with waits between them"],
        ["Pausing and resuming a rule", "**Pause** / **Resume** on the journey card"],
        ["The Recent runs log", "**Recent journey runs** on the Journeys page, and **Activity & traces** for the full picture"],
      ] },
      { type: "h", text: "What is better than before" },
      { type: "list", items: [
        "**More than one action.** A rule did one thing. A journey does a sequence — notify the team, wait a day, send an email, create a follow-up task.",
        "**Waits.** A journey can pause for minutes, hours or days between steps, or park until something actually happens to that person.",
        "**Versions.** Editing a live journey creates a draft. The published version keeps running until you publish the new one, so you can revise without breaking what is running.",
        "**A real explanation.** The activity trace tells you why a journey did or did not enrol someone, and what each run actually did, step by step.",
        "**Re-enrolment control.** You choose what happens when the same person qualifies again — see \"What happens when the same person is enrolled twice\".",
      ] },
      { type: "h", text: "One thing to check" },
      { type: "p", text: "Converted rules and any journey that existed before re-enrolment control was added were left on the **parallel** run mode, because that is what they had always done. New journeys start on **single**. If a converted rule is now sending twice to the same person, that is the setting to look at first." },
      { type: "callout", tone: "warning", text: "Journeys are owner/admin-only, from viewing through publishing. If you could edit automation rules before and cannot see Journeys now, ask an owner about your access." },
      { type: "p", text: "There is still a **Settings → Automations** tab, but it holds only one setting now: **Next-step scheduling**, which controls when a journey's auto-created follow-up task falls due. Everything else lives in the journey builder." },
    ],
  },
  {
    slug: "journeys-overview",
    title: "Journeys: multi-step automations",
    summary: "What a journey is, how versions and runs work, and how to install ready-made starter drafts.",
    category: "marketing",
    audience: "admins",
    keywords: [
      "journeys",
      "journey",
      "lifecycle",
      "automation",
      "automation rule",
      "advanced automation",
      "marketing journey",
      "versioning",
      "templates",
      "recommended drafts",
      "runs",
    ],
    body: [
      { type: "p", text: "A journey is a **versioned, multi-step workflow**. Something happens to a lead or a contact, the journey enrols them, and then it works through its steps over time — messages, waits, CRM actions, branches. Find them under **Automation → Journeys**." },
      { type: "p", text: "This is the only automation engine in the app. The old one-trigger, one-action automation rules were retired and converted into journeys — see \"Automation rules are now journeys\" if you are looking for something you built there." },
      { type: "h", text: "Key concepts" },
      { type: "list", items: [
        "**Category** — each journey is a CRM automation or a Marketing journey. Marketing journeys respect marketing consent; CRM automations are operational.",
        "**Versions** — edits create a new draft. Publishing makes that version active and retires the previous one. A running person keeps the version they started on, for life.",
        "**Status** — draft, active, paused or archived. A journey must be published before it can be activated, and a paused journey enrols nobody.",
        "**Runs** — each enrolled lead or contact becomes a run you can trace, retry or cancel.",
        "**Run mode** — what happens if the same person is enrolled again while a run is still open. Shown on every journey card as a **re-enrol:** badge.",
      ] },
      { type: "h", text: "What the Journeys page shows you" },
      { type: "list", items: [
        "**Journey library** — every journey, with its status, category, re-enrol mode, active version and run count. Open **Edit** on any card to change it as a new draft.",
        "**Recent journey runs** — the last runs across all journeys, with the record, version, status, current step and any error. **Trace** opens the full timeline; **Retry** picks up a failed or cancelled run; **Cancel** stops one that is queued or waiting.",
        "**Activity & traces** — the diagnostic view: which triggers have ever fired, and what every journey decided about every event.",
      ] },
      { type: "h", text: "Start from recommended drafts" },
      { type: "p", text: "Click **Install recommended drafts** to add four ready-made journeys as drafts you can review, edit and publish:" },
      { type: "table", headers: ["Journey", "What it does"], rows: [
        ["New lead speed-to-contact", "Instantly notifies the team and creates a same-day follow-up task"],
        ["Won-customer welcome", "Sends a welcome email a day after a lead is won"],
        ["Purchase anniversary", "Annual anniversary greeting for vehicle owners"],
        ["Service win-back", "Re-engages owners inactive for 12 months, then follows up"],
      ] },
      { type: "callout", tone: "warning", text: "If the legacy anniversary or win-back toggles are still on in Settings, a banner warns you to disable them before activating equivalent journeys — otherwise customers could receive both versions." },
      { type: "callout", tone: "info", text: "Journeys are owner/admin-only, from viewing through publishing." },
    ],
  },
  {
    slug: "journeys-build-and-publish",
    title: "Journeys: build, publish and monitor runs",
    summary: "Set a journey's trigger, re-enrolment behaviour, entry filters and steps, publish a version, and manage the runs it creates.",
    category: "marketing",
    audience: "admins",
    keywords: [
      "journey builder",
      "steps",
      "trigger",
      "publish",
      "draft",
      "enroll",
      "enrol",
      "runs",
      "automation rule",
      "continue on error",
      "keep going if this step fails",
      "placeholders",
      "merge fields",
    ],
    body: [
      { type: "p", text: "The builder has four numbered parts. Save your work as a **draft**, then publish it to go live. Editing a live journey always creates a new draft — the published version keeps running until you publish the replacement." },
      { type: "h", text: "1. Enrollment trigger" },
      { type: "p", text: "What puts someone into the journey. Some triggers need a detail — a stage, a number of idle days, a segment plus how often to re-enrol, or a number of inactive months." },
      { type: "table", headers: ["Triggers that fire on an event", "Triggers the system sweeps for"], rows: [
        ["New lead created", "Lead sits idle for N days"],
        ["Lead enters a stage", "Contact joins a saved segment"],
        ["Lead won / Lead lost", "Purchase anniversary"],
        ["Quote signed / Quote declined", "Inactive customer win-back"],
        ["Vehicle delivered, Referral earned", "—"],
      ] },
      { type: "callout", tone: "tip", text: "Before you build on a trigger, open **Activity & traces** and check that trigger has actually fired in your workspace. A journey built on a trigger nothing produces activates cleanly, looks correct, and enrols nobody — with no error to see." },
      { type: "h", text: "2. If the same person is enrolled again" },
      { type: "p", text: "Four choices — **Single**, **Restart**, **Queued**, **Parallel** — deciding what becomes of a run already in flight. This matters more than it sounds; it has its own guide, \"What happens when the same person is enrolled twice\"." },
      { type: "h", text: "3. Optional entry filters" },
      { type: "p", text: "Narrow enrolment by **lead source** (comma-separated), **province**, and/or a **minimum lead value** in rands. All the filters you set must match, or the person is not enrolled — and the trace says so, in those words." },
      { type: "h", text: "4. Journey steps" },
      { type: "p", text: "Add steps with **+ Add step** and order them with the up/down arrows. The steps you can build in the form:" },
      { type: "list", items: [
        "**Send email** — pick a template, or write a subject and body.",
        "**Send SMS** — a message.",
        "**Notify the team** — a push notification to staff.",
        "**Create activity** — a call, email, meeting, WhatsApp or to-do, with a summary, due days and an owner (defaults to the lead or contact owner).",
        "**Wait** — a number of minutes, hours or days before the next step.",
        "**Move lead stage**, **Assign lead**, **Add contact tag**, **Remove contact tag**.",
        "**Condition / branch** — matching records continue; non-matches stop safely.",
        "**Stop journey** — end the run here, with a reason.",
      ] },
      { type: "p", text: "Four more step types exist and are more powerful, but have **no visual editor yet** — **Choose (branches)**, **Repeat (loop)**, **Wait for an event** and **Set variables**. They appear in the step list with an amber panel and a short summary, and are carried through untouched when you edit the rest of the journey. See the separate guides for what each one does." },
      { type: "h", text: "If a step fails" },
      { type: "p", text: "By default a failed step fails the whole run. The run is retried, but only **three times** in total, after which it stays failed." },
      { type: "p", text: "Tick **Keep going if this step fails** on any step that is a nice-to-have rather than the point of the journey — a courtesy SMS, say — and a provider outage on that one step will not kill the run. The trace records it as **Continued past error** so nothing is hidden. The tick box is offered on the sending and CRM steps and on Condition; not on Wait or Stop, where it would mean nothing." },
      { type: "callout", tone: "info", text: "A **Stop journey** step, a condition that does not match, and a journey the engine deliberately abandons are decisions, not faults — \"Keep going if this step fails\" never overrides them." },
      { type: "h", text: "Placeholders" },
      { type: "p", text: "Message subjects and bodies substitute these. The builder's hint text names only the first four, but all of them work:" },
      { type: "table", headers: ["Placeholder", "What it fills in"], rows: [
        ["**{{first_name}}**", "The contact's first name, or the first word of the lead's name. Falls back to \"there\", so a greeting never comes out blank."],
        ["**{{name}}**", "The contact's or lead's full name. Falls back to \"Customer\"."],
        ["**{{model}}**", "The vehicle or product the journey is about — from the event where it has one (anniversary and win-back journeys), otherwise the lead's product."],
        ["**{{value}}**", "The lead value in rands, rounded."],
        ["**{{email}}** / **{{phone}}**", "The contact's or lead's email and phone."],
        ["**{{stage}}**", "The lead's current stage name."],
        ["**{{company}}**", "The contact's company."],
        ["**{{years}}**", "How many years the anniversary is for. Empty on every other trigger."],
        ["**{{var_yourname}}**", "Any variable the journey has set — see the Variables guide."],
        ["**{{repeat_index}}** / **{{repeat_item}}**", "Where a loop has got to. Only inside a Repeat step."],
      ] },
      { type: "callout", tone: "info", text: "A placeholder with nothing behind it renders as nothing rather than breaking the send — so proofread with a **Test on a lead** rather than assuming a blank means the merge field is wrong." },
      { type: "h", text: "Ceilings" },
      { type: "list", items: [
        "**100 steps** in a journey, counting every step at every level — steps nested inside branches and loops count too.",
        "**5 levels** of nesting.",
        "**30 conditions** in one condition group.",
        "**10 options** on a Choose step, **100 iterations** on any loop.",
      ] },
      { type: "h", text: "Publish and run" },
      { type: "steps", items: [
        "**Save draft** stores your changes as a new draft version.",
        "Click **Publish v{n}** to make that version active.",
        "Use **Pause** / **Resume** to control an active journey. Pausing stops new enrolments.",
        "For idle-lead, segment, anniversary and win-back journeys, **Enroll now** sweeps for matching records immediately instead of waiting for the next scheduled pass.",
        "Use **Test on a lead** to run the journey end to end against one real lead — read that guide first, because it really sends.",
        "**Archive** retires a journey.",
      ] },
      { type: "h", text: "Monitor runs" },
      { type: "p", text: "**Recent journey runs** at the bottom of the Journeys page shows each run's journey, record, version, status, current step, start time and any error. **Retry** failed or cancelled runs; **Cancel** runs that are still queued or waiting; **Trace** opens the step-by-step timeline." },
      { type: "callout", tone: "tip", text: "Editing a published journey creates a fresh draft — the live version keeps running until you publish the new one, so you can revise safely. Anyone already part-way through keeps the version they started on." },
    ],
  },
  {
    slug: "journeys-run-modes",
    title: "Journeys: what happens when the same person is enrolled twice",
    summary: "The four re-enrolment modes — single, restart, queued and parallel — the per-person cap, and why old journeys behave differently from new ones.",
    category: "marketing",
    audience: "admins",
    keywords: [
      "run mode",
      "re-enrol",
      "re-enroll",
      "reenrol",
      "enrolled twice",
      "duplicate",
      "sent twice",
      "double email",
      "single",
      "restart",
      "queued",
      "parallel",
      "cap",
      "open runs",
      "automation rule",
    ],
    body: [
      { type: "p", text: "A lead can qualify for the same journey more than once — a stage changed twice in an afternoon, a quote declined and then re-signed. If a run for that person is **still open**, the journey has to decide what the second enrolment means. That decision is the journey's **run mode**." },
      { type: "p", text: "Set it in the builder under **2. If the same person is enrolled again**. It is a property of the journey, not of a version, so changing it takes effect without republishing. Every journey card shows the current setting as a **re-enrol:** badge." },
      { type: "h", text: "The four modes" },
      { type: "table", headers: ["Mode", "What happens to the run already going", "Choose it when"], rows: [
        ["**Single**", "It wins. The second enrolment is dropped while it is still open.", "The sequence should happen once. This is the default for new journeys and the safest answer."],
        ["**Restart**", "It is cancelled, and the new enrolment replaces it from step one.", "Only the latest trigger matters — a fresh enquiry should reset the follow-up clock rather than run beside the old one."],
        ["**Queued**", "It finishes first. The new enrolment is parked and starts when the open run closes.", "Both enrolments deserve the sequence, but not at the same time."],
        ["**Parallel**", "Nothing. Both runs continue side by side, and **both of them send**.", "Rarely. Two live sequences means the same person can receive the same message twice."],
      ] },
      { type: "callout", tone: "warning", text: "**Parallel** is the only mode where one person can be in two live sequences at once, so it is the only one badged as something to notice rather than a neutral fact. If customers are receiving duplicates, check this setting first." },
      { type: "h", text: "Old journeys and new journeys differ, deliberately" },
      { type: "p", text: "Journeys that existed before run modes were added — including every automation rule that was converted into a journey — were left on **parallel**, because running side by side is what they had always done. Switching them to single would have quietly changed live behaviour on journeys nobody had reviewed." },
      { type: "p", text: "New journeys start on **single**. So an old journey and a new one can sit next to each other in the library doing opposite things on a second enrolment. Nothing changes a journey's mode except the control in the builder — not publishing, not editing, not saving a draft." },
      { type: "callout", tone: "tip", text: "Worth doing once: open the Journeys page and read the **re-enrol:** badges down the list. Anything showing **parallel** that you did not deliberately choose is a candidate for **single**." },
      { type: "h", text: "The cap: ten open runs per person, per journey" },
      { type: "p", text: "Whatever the mode, one person may have at most **10 open runs** on one journey. Beyond that, further enrolments are dropped and the trace records **\"already has 10 open runs (the per-person cap)\"**." },
      { type: "p", text: "This applies to every mode, **parallel included** — parallel is the one that piles up fastest, because it never looks at the open runs at all. It matters most for **queued**: without a ceiling, a lead whose stage changes twenty times in an afternoon would park twenty runs, and they would then drain one after another and send twenty times, days after the activity that caused them." },
      { type: "h", text: "What a repeat of the same event does" },
      { type: "p", text: "Run modes only cover a **different** event reaching the same person. The identical event arriving twice — a retry, a duplicated write — is caught separately and reported in the trace as **\"already enrolled for this event\"**. That one is the system working correctly, not a refusal you need to act on." },
      { type: "h", text: "Reading a queued run" },
      { type: "p", text: "A run parked behind another shows the status **blocked** and does not start on a timer — it is released when its predecessor actually closes, whenever that is. In the trace its enrolment reason reads **\"queued behind an open run (run mode: queued)\"**." },
    ],
  },
  {
    slug: "journeys-test-on-a-lead",
    title: "Journeys: test a journey on a real lead",
    summary: "Run a published journey end to end against one lead you choose — and understand that it genuinely sends.",
    category: "marketing",
    audience: "admins",
    keywords: [
      "test",
      "test run",
      "try",
      "dry run",
      "preview",
      "test on a lead",
      "run it for real",
      "manual run",
      "journey test",
      "automation rule",
    ],
    body: [
      { type: "p", text: "Every journey card with a published version has a **Test on a lead** button. It enrols one lead you pick, immediately, and walks the journey's steps." },
      { type: "callout", tone: "warning", text: "**This is not a dry run.** The steps execute for real — emails, SMS, push notifications, stage moves and tasks all happen, to that lead and to whoever the steps notify. There is no undo on a sent message." },
      { type: "p", text: "That is a deliberate choice, not a missing feature. A simulated run would prove the journey walks from step to step, which is the half that rarely breaks. The half that breaks is the message itself — the wording, the merge fields, the consent gate — and only a real send exercises those." },
      { type: "h", text: "Run a test" },
      { type: "steps", items: [
        "Make sure the journey is **active**. A paused journey refuses the test with \"Activate the journey first — a paused journey enrols nobody.\"",
        "On the journey's card, click **Test on a lead**.",
        "Pick a lead under **Lead to run against**. The list shows open leads only.",
        "Read the amber banner naming the lead — it will really be contacted.",
        "Click **Run it for real**.",
        "Read the result, then open the trace to see the whole path the run took.",
      ] },
      { type: "callout", tone: "tip", text: "Use a lead you own, or one you created for testing, with your own email address and mobile number on it. Then a mistake in a template costs you an email rather than a customer." },
      { type: "h", text: "Reading the result" },
      { type: "list", items: [
        "**Enrolled — run is …** with a short run reference. The journey accepted the lead and the run has the status shown.",
        "**Nothing was sent** with a reason. The journey declined to enrol this lead, and the reason is the real one — entry conditions, the per-person cap, a duplicate, or the trigger not matching. Nothing was sent to anybody.",
        "**Parked behind a run already open for this lead** — that is run mode **queued** doing its job. The test run will start when the other one finishes, not now.",
      ] },
      { type: "h", text: "What the test does and does not touch" },
      { type: "list", items: [
        "It drives **only** the event it created and the single run that event produced. It does not push anybody else's due runs along.",
        "It respects the journey's **run mode** and the per-person cap exactly as a real enrolment would.",
        "It is recorded in the **audit log**, so there is a record of who tested what and when.",
        "It appears in **Activity & traces** like any other run, with its own timeline.",
      ] },
      { type: "callout", tone: "info", text: "Testing is owner/admin-only, like everything else on the Journeys page." },
    ],
  },
  {
    slug: "journeys-activity-trace",
    title: "Journeys: the activity trace — why a journey did or did not run",
    summary: "See which triggers have ever fired, what every journey decided about every event, and the exact path a single run took.",
    category: "marketing",
    audience: "admins",
    keywords: [
      "trace",
      "activity",
      "why didn't it run",
      "not enrolled",
      "debug",
      "troubleshoot",
      "history",
      "run history",
      "step timeline",
      "trigger never fired",
      "retention",
      "automation rule",
    ],
    body: [
      { type: "p", text: "A journey that enrolled nobody looks exactly like a journey that matched nobody — both are silence. The **activity trace** is what tells them apart. Open it with **Activity & traces** at the top of the Journeys page." },
      { type: "h", text: "Triggers — last 30 days" },
      { type: "p", text: "Every trigger the builder offers, with how many events of that type the system has seen, and a label: **Firing**, **Quiet**, or **Never fired**." },
      { type: "p", text: "**Never fired** is the one that matters. A journey built on a trigger that has never fired will activate, look completely correct, and enrol nobody forever — because nothing ever reaches it. If any trigger has never fired, a warning appears at the top of the page naming it. Either the event is genuinely rare in your dealership, or nothing in the app produces it yet." },
      { type: "h", text: "Recent events, and what each journey decided" },
      { type: "p", text: "Below that, the recent events the engine has seen. Under each one is every active journey that was weighed against it, with a tick or a dash and the actual reason. These are the reasons you will see:" },
      { type: "table", headers: ["Verdict", "What it means"], rows: [
        ["**enrolled**", "A run was created."],
        ["queued behind an open run (run mode: queued)", "A run was created but is parked until the open one finishes."],
        ["listens for \"…\", not \"…\"", "This journey's trigger is a different event. Normal — every active journey is weighed against every event."],
        ["trigger filters did not match", "Right event, wrong detail — for example a stage-entered journey watching a different stage."],
        ["entry conditions did not match", "The lead source, province or minimum value filter excluded this person."],
        ["already enrolled for this event", "The identical event reached the journey twice. The duplicate was ignored — this is correct behaviour."],
        ["a run is already open and this journey is set to \"single\"", "Re-enrolment was dropped by the run mode."],
        ["already has 10 open runs (the per-person cap)", "This person has hit the ceiling on open runs for this journey."],
        ["no published version", "The journey is active but has nothing published to run."],
        ["the published version has no first step", "The published version has no steps to start with."],
        ["the lead or contact no longer exists", "The record was deleted between the event and the enrolment."],
      ] },
      { type: "callout", tone: "info", text: "Older events may say the verdicts were not kept — those were recorded before decision tracing existed. \"No active journey was considered\" means nothing was listening at all." },
      { type: "h", text: "One run, step by step" },
      { type: "p", text: "Click **Trace** next to any run — on this page or in **Recent journey runs** — to open its timeline. It is an indented list in execution order, not a diagram." },
      { type: "list", items: [
        "Each step shows its name, type, outcome, how long it took and when, plus its position in the journey.",
        "A **condition** shows every clause with the value it actually saw, so you do not have to reconstruct why it went the way it did against a lead that has since changed.",
        "A **Choose** step lists **every** branch, each marked **Taken** or **Not taken** — the branches not taken are as informative as the one that was. The branch that ran is expanded.",
        "A **Repeat** step shows how many iterations ran out of how many were planned, with each iteration expandable; failed and held iterations, plus the first and last, open automatically.",
        "A step **held** rather than run — by quiet hours or a sending cap — says so, with the time it will be tried again. Held is not sent.",
        "For a run still going, a dashed box shows the live head: the step it is **about** to take and when it is due. No step log can show that, because it has not happened yet.",
      ] },
      { type: "callout", tone: "tip", text: "The trace is drawn against the version the run was **pinned** to, not the journey as it is now. So if you have already edited the journey to fix a problem, the trace still shows you what the run actually saw." },
      { type: "h", text: "The trace is not kept forever" },
      { type: "p", text: "Traces are diagnostic, not a business record, and they are the fastest-growing data in the app. They are pruned automatically:" },
      { type: "list", items: [
        "**Events** are removed after **45 days**, once the engine has finished with them. Events still waiting to be processed are never removed.",
        "**Runs** are removed after **60 days**, and only once they have closed — completed, failed or cancelled. A run still in flight is live state, not a trace, and is never pruned.",
        "**The 20 most recent runs of every journey are always kept**, however old they are. A quiet journey that runs twice a year is exactly the one you are most likely to be investigating, so age alone must not empty its trace.",
        "Removing a run takes its step timeline with it.",
      ] },
      { type: "callout", tone: "warning", text: "If you need to keep evidence of what a journey sent someone — a complaint, a dispute — capture it while it is there. Open an old **Trace** link after the run has been pruned and you get \"That run is not available.\"" },
    ],
  },
  {
    slug: "journeys-branches-and-loops",
    title: "Journeys: branches and loops",
    summary: "Choose steps for real branching, Repeat steps for loops, the loop variables available inside them — and the fact that both are authored as JSON.",
    category: "marketing",
    audience: "admins",
    keywords: [
      "branch",
      "branches",
      "choose",
      "loop",
      "loops",
      "repeat",
      "count",
      "while",
      "until",
      "for each",
      "for_each",
      "iteration",
      "repeat.index",
      "json",
      "advanced",
      "automation rule",
    ],
    body: [
      { type: "p", text: "Two step types give a journey real control flow: **Choose (branches)** picks one path out of several, and **Repeat (loop)** runs a sequence of steps more than once." },
      { type: "callout", tone: "warning", text: "**Neither has a visual editor yet.** Both are authored as JSON, outside the builder form. In the builder they show as an amber panel with a one-line summary and this note: \"There is no visual editor for this step yet — it is authored as JSON. It is carried through this form exactly as saved, so editing the rest of the journey cannot damage it.\" The type dropdown is locked on those steps so a stray click cannot wipe the branches. Everything else in the journey stays fully editable." },
      { type: "p", text: "In practice that means asking whoever configures your workspace to set one up. This article explains what they do so you can specify what you want and read the trace afterwards." },
      { type: "h", text: "Choose: one path out of several" },
      { type: "p", text: "A Choose step holds a list of options. Each option has its own conditions and its own sequence of steps. The **first** option whose conditions match is the one that runs — the rest are not even evaluated. An optional **default** sequence runs when nothing matched." },
      { type: "p", text: "If nothing matches and there is no default, the run simply carries on with the step after the Choose. Up to **10 options** per Choose step." },
      { type: "callout", tone: "info", text: "This is what the ordinary **Condition / branch** step cannot do inside a sequence. At the top level a condition is a two-way branch; inside a branch or a loop it is a gate — if it does not match, the run stops there. Use Choose when you want an \"otherwise\"." },
      { type: "h", text: "Repeat: four kinds of loop" },
      { type: "table", headers: ["Mode", "How it decides to go round again"], rows: [
        ["**count**", "A fixed number of passes, from 1 to 100."],
        ["**while**", "Conditions are checked **before** each pass. Stops the first time they do not hold. Must have at least one condition, or it would never end."],
        ["**until**", "The sequence always runs **at least once**, then the conditions are checked. It keeps going while they are still false."],
        ["**for_each**", "One pass per item in a list, up to 100 items. The list is photographed when the loop starts, so it iterates what it began with even if the record changes while the run is parked."],
      ] },
      { type: "callout", tone: "warning", text: "Every loop, of every mode, stops at **100 iterations**. A `while` whose conditions never turn false is the classic runaway automation; hitting the ceiling fails the run with a message naming the loop rather than spinning on forever. But 100 iterations of real work is already far more than a journey should be doing to one person — treat hitting it as a design fault." },
      { type: "h", text: "Loop variables" },
      { type: "p", text: "Steps inside a Repeat can read where the loop has got to, in conditions and in the branching of a nested Choose:" },
      { type: "table", headers: ["Variable", "What it holds"], rows: [
        ["**repeat.index**", "Which pass this is, counting from **1**. The first pass is 1, not 0."],
        ["**repeat.first**", "True on the first pass."],
        ["**repeat.last**", "True on the final pass — meaningful only in **for_each**, where the total is known in advance. In count, while and until loops it is always false."],
        ["**repeat.item**", "The current item — **for_each** only. Empty in the other three modes."],
      ] },
      { type: "p", text: "The innermost loop wins: inside nested loops, these refer to the loop the step is directly in." },
      { type: "p", text: "Two of them can also go straight into a message: **{{repeat_index}}** and **{{repeat_item}}** work in a subject or body of any step inside the loop, and render as nothing outside one." },
      { type: "h", text: "Reading a branch or a loop in the trace" },
      { type: "p", text: "The activity trace is where this becomes legible. A Choose step lists every branch with **Taken** or **Not taken**, and a Repeat step lists its iterations one by one — so \"which way did it go, and on which pass\" is a question you can actually answer. Each iteration is recorded separately, so the third time round is distinguishable from the first." },
      { type: "h", text: "Limits" },
      { type: "list", items: [
        "**5 levels** of nesting. A branch inside a loop inside a branch is already at three.",
        "**100 steps** in total across the whole journey, counting everything inside every branch and loop.",
        "**10 options** per Choose, **100 iterations** per loop, **100 items** per for_each.",
        "A branch or loop sequence must contain at least one step; an empty one is rejected when the journey is saved.",
      ] },
    ],
  },
  {
    slug: "journeys-wait-for-an-event",
    title: "Journeys: waiting for something to happen",
    summary: "Park a run until a named event arrives for that person, with a required timeout and a choice of what to do when it runs out.",
    category: "marketing",
    audience: "admins",
    keywords: [
      "wait for an event",
      "wait_for_trigger",
      "wait for trigger",
      "park",
      "timeout",
      "until",
      "reply",
      "quote signed",
      "chase",
      "follow up",
      "json",
      "automation rule",
    ],
    body: [
      { type: "p", text: "The ordinary **Wait** step waits for a length of time. **Wait for an event** waits for something to actually happen: it parks the run until one of the events you name arrives **for that same person**." },
      { type: "p", text: "That is what lets a journey stop chasing. \"Send the quote, then wait up to seven days for it to be signed; if it is signed, carry on to the handover sequence; if it is not, send the reminder.\"" },
      { type: "callout", tone: "warning", text: "Like branches and loops, this step has **no visual editor yet** — it is authored as JSON. The builder shows it as an amber panel summarising what it watches and how long for, and carries it through untouched while you edit the rest of the journey." },
      { type: "h", text: "What it can wait for" },
      { type: "p", text: "Up to **five** of the event triggers, and any one of them arriving is enough to wake the run: new lead created, lead enters a stage, lead won, lead lost, quote signed, quote declined, vehicle delivered, referral earned." },
      { type: "callout", tone: "info", text: "The swept triggers — idle lead, contact segment, purchase anniversary, win-back — **cannot** be waited for. Nothing writes an event for those; the system finds matching records by sweeping them on a schedule, so a wait on one would be a guaranteed timeout dressed up as a feature. The journey refuses to save if you try." },
      { type: "h", text: "The timeout is required" },
      { type: "p", text: "Every wait must have a deadline, from **one minute to 30 days**. There is no \"wait forever\" — a run parked indefinitely is a row in the database quietly asking the same question on every pass until somebody notices, which could be never." },
      { type: "p", text: "You also choose what a timeout means:" },
      { type: "list", items: [
        "**Carry on** (the default) — the deadline passes, the run moves to the next step anyway. This is the shape you want for a chase sequence.",
        "**Stop** — the deadline passes and the run ends. Use it when the rest of the journey only makes sense if the thing happened.",
      ] },
      { type: "h", text: "How it behaves" },
      { type: "list", items: [
        "Only events from **the moment the wait started** count. Something that happened before the run reached this step will not wake it.",
        "The **first** matching event wins, and the wait stops listening.",
        "An event that genuinely arrived inside the window is honoured even if the system checks a little late — the question is whether the thing happened, not whether the check was punctual. An event that arrives **after** the deadline does not extend the wait.",
        "Inside a **Repeat**, each pass arms its own wait. Iteration two does not wake instantly on the event that resolved iteration one — which is exactly what you want in a \"chase them twice\" journey.",
        "The run re-checks about once a minute, but never sooner than the engine's own scheduled pass.",
      ] },
      { type: "callout", tone: "tip", text: "The trace records the whole wait, not the last minute of it — you can see how long a run sat, and whether it moved on because the event arrived or because the clock ran out." },
    ],
  },
  {
    slug: "journeys-variables",
    title: "Journeys: variables",
    summary: "Set named values during a run and reuse them in later messages and conditions.",
    category: "marketing",
    audience: "admins",
    keywords: [
      "variables",
      "variable",
      "set variables",
      "vars",
      "placeholder",
      "merge field",
      "template",
      "json",
      "automation rule",
    ],
    body: [
      { type: "p", text: "A **Set variables** step stores named values on the run. Later steps can drop them into message text and test them in conditions, so a journey can decide something once and reuse the answer all the way through." },
      { type: "callout", tone: "warning", text: "This step has **no visual editor yet** — it is authored as JSON, like branches, loops and Wait for an event. The builder shows it as an amber panel listing the names it sets, and carries it through unchanged while you edit the rest of the journey." },
      { type: "h", text: "How to refer to one" },
      { type: "table", headers: ["Where", "How you write it", "Example"], rows: [
        ["In a message body or subject", "**{{var_ + the name}}**", "A variable called `offer` is written **{{var_offer}}**"],
        ["In a condition", "**vars. + the name**", "A variable called `offer` is the field **vars.offer**"],
      ] },
      { type: "callout", tone: "info", text: "Note the difference: templates need the **var_** prefix, conditions need the **vars.** prefix. Variables always live under their own name, which is what stops one ever being confused with the lead's, the contact's or the loop's own values." },
      { type: "h", text: "Rules to know" },
      { type: "list", items: [
        "A name starts with a letter and then allows letters, numbers and underscores, up to 40 characters.",
        "Values are text. A step can set up to **10** of them, and each rendered value is capped at **500 characters**.",
        "Setting a name again **overwrites** it; everything else the run has set is kept. That is what makes a Set variables step useful inside a loop.",
        "Variables survive for the life of the run, including across waits that last days.",
        "Across the whole run, all the variables together are capped at **4,000 bytes** — roughly eight full-length values. A run that would go past it is stopped rather than retried, because rendering the same templates again would produce the same size.",
      ] },
      { type: "callout", tone: "tip", text: "Variables are values you compute, not a place to stash records. If a journey is accumulating text on every pass of a loop, it will hit the ceiling and stop — which is the ceiling working, not a fault to route around." },
    ],
  },
];
