import type { HelpArticle } from "../types";

export const xAndAttentionArticles: HelpArticle[] = [
  {
    slug: "connect-x-social-inbox",
    title: "Connect X to the Social inbox",
    summary: "Set up one X account for your workspace to receive DMs, mentions and replies and turn them into CRM leads.",
    category: "comms",
    audience: "admins",
    keywords: ["X", "Twitter", "connect X", "X integration", "OAuth", "PKCE", "webhook", "X Activity API", "DM", "mentions", "replies", "Grok"],
    body: [
      { type: "p", text: "The X integration brings **direct messages, mentions and replies** into the existing Social inbox. A new person is created as a contact, an open CRM lead is created or reused, and future X activity stays on that customer thread. Each workspace connects **one X account**; another tenant's account, tokens and conversations are never used as a fallback." },
      { type: "h", text: "Before you start" },
      { type: "list", items: [
        "You must be a workspace **owner**.",
        "Create or choose a Project and App in the **X Developer Portal** with OAuth 2.0 enabled.",
        "Add **/api/integrations/x/callback** on your CRM domain as an OAuth 2.0 callback address in X.",
        "The X app needs **Read, Write and Direct Message** access. The CRM requests **tweet.read**, **users.read**, **dm.read**, **dm.write** and **offline.access** through OAuth 2.0 Authorization Code with PKCE.",
        "Your X plan must include the X Activity and Direct Message capabilities you intend to use.",
      ] },
      { type: "h", text: "Configure and connect the workspace" },
      { type: "steps", items: [
        "Open **Settings → Integrations → X**.",
        "Save the X app's **OAuth 2 client ID**, **client secret** and **webhook signing secret**. Secret fields are encrypted and are never shown in the page after saving.",
        "Click **Connect X account**. Sign in to the correct X account and approve the requested access.",
        "After X returns you to the CRM, confirm that the card says **Connected @username**. Connecting another account replaces this workspace's previous active X account; an account already owned by another workspace is refused.",
        "Copy the complete **Webhook callback URL** now shown in the card. It includes the connected account ID, which is how a webhook is resolved to the correct tenant before CRM data is touched.",
      ] },
      { type: "h", text: "Register the webhook and activity subscriptions" },
      { type: "steps", items: [
        "In the X Developer Console, register the HTTPS webhook URL copied from Settings. The endpoint supports X's Challenge-Response Check (CRC).",
        "Subscribe the connected account to **dm.received**, **post.mention.create** and **post.reply.create** in the X Activity API.",
        "Send a DM to the connected account from a different X user, then mention it in a post. Both should appear under **Social inbox → X**.",
        "Open the created lead and confirm the source is **X**. Reply to the DM from the Social inbox to verify **dm.write** access.",
      ] },
      { type: "callout", tone: "warning", text: "Do not use the old Account Activity implementation as a setup guide. This integration consumes the current **X Activity API envelope** and verifies every POST with X's HMAC signature before it writes anything." },
      { type: "h", text: "Optional Grok reply drafts" },
      { type: "steps", items: [
        "In the same X integration card, save a tenant-specific **xAI API key** and model. The default model shown by the CRM is **grok-4.6**.",
        "Set **Allow Grok reply drafts** to **true**. The API key alone does not enable data sharing.",
        "Open an X conversation and click **Draft with Grok**. Review and edit the result, then send it yourself. Grok never auto-sends a DM or public reply.",
      ] },
      { type: "callout", tone: "info", text: "For Grok drafts the CRM sends at most six recent messages, truncates long entries and redacts common email addresses and phone numbers first. The setting, key and conversation lookup are tenant-bound. Leave drafting disabled if your data policy does not permit sending conversation context to xAI." },
      { type: "h", text: "If X stops working" },
      { type: "list", items: [
        "**No Connect button result** — confirm the client ID and secret, and make sure the callback URL in X exactly matches the CRM callback.",
        "**Webhook validation fails** — confirm the complete callback URL includes **account_id**, uses public HTTPS with no custom port, and the webhook secret is the app consumer secret.",
        "**Events do not arrive** — confirm all three X Activity subscriptions are active for the connected user ID. Outbound echoes are deliberately ignored.",
        "**Replies say Reconnect X** — reconnect from Settings. The CRM refreshes expiring access tokens when possible; a revoked grant requires a fresh OAuth approval.",
        "**Wrong workspace or account** — stop. Do not copy tokens between tenants. Reconnect while signed into the intended workspace and X account.",
      ] },
    ],
  },
  {
    slug: "attention-centre-guide",
    title: "Use the Attention Centre",
    summary: "Understand why a deal appears, how items are ranked, and how unanswered X conversations are surfaced.",
    category: "crm",
    audience: "everyone",
    keywords: ["attention", "attention centre", "needs attention", "customer waiting", "X waiting", "unanswered inbound", "snooze", "dismiss", "no next step", "overdue"],
    body: [
      { type: "p", text: "The Attention Centre is a ranked work queue for **open deals with a specific reason to act**. It is not a list of every lead and it is not the same as unread: a message can be read and still be waiting for a reply." },
      { type: "h", text: "What creates an attention item" },
      { type: "table", headers: ["Signal", "When it appears", "What to do"], rows: [
        ["Customer waiting", "The latest conversation direction is inbound and no reply has been recorded for four hours. This includes WhatsApp, Messenger, Instagram and **X DMs, mentions and replies** when they are linked to the lead.", "Open the Social inbox thread and reply."],
        ["Overdue task", "A planned activity passed its due time.", "Complete, reschedule or replace the activity."],
        ["No next step", "The open lead has no planned activity.", "Add the next concrete action."],
        ["Quote expiring", "A sent, unsigned quote is expired or approaching its validity date.", "Follow up, revise or close it."],
        ["Stage age", "The lead has stayed beyond that stage's configured stale threshold.", "Progress, move or close the deal."],
      ] },
      { type: "p", text: "Customer waiting carries the highest individual weight, so a customer who has written and received no answer rises quickly. Several reasons can apply to the same lead; their combined score determines whether the row is **Urgent**, **Act** or **Watch**." },
      { type: "h", text: "X conversations in Attention" },
      { type: "list", items: [
        "An inbound X event creates or reuses an X contact and open lead before the conversation is filed.",
        "If staff do not reply, the lead receives **Customer wrote on X … and has had no reply** after four hours.",
        "The action opens that exact Social inbox conversation. A mention or reply is captured for follow-up, while the existing composer sends private DM replies only.",
        "Replying changes the conversation's latest direction to outbound and removes the waiting signal on the next refresh.",
      ] },
      { type: "h", text: "Filters and set-aside controls" },
      { type: "list", items: [
        "Use **Mine**, **Unassigned** or **Everyone** to change ownership scope. The default full queue does not silently hide a colleague's accessible item.",
        "Filter reasons by **Customer waiting**, **Commitments** or **Workflow**.",
        "**Snooze** hides one reason until a chosen time. **Dismiss** removes that reason until the underlying facts materially change. Both require a reason and are audited.",
        "A lead that keeps returning after snoozes is marked so the team can decide whether to progress or close it.",
      ] },
      { type: "callout", tone: "warning", text: "The Attention Centre follows the same tenant and record permissions as the leads board. It never widens access: if you cannot open a lead or conversation normally, it cannot appear here." },
      { type: "callout", tone: "tip", text: "If the page says **Nothing is waiting**, it means no accessible open deal currently has one of these signals. It does not claim that every deal is healthy, and connection problems belong under **Settings → Integrations**, not in a customer's deal queue." },
    ],
  },
];
